openapi: 3.0.0
info:
  title: Inventory Microservice
  description: |
    This is the inventory microservice.
  contact:
    email: terry.chan@hohokusinc.com
  version: 1.0.0
servers:
- url: /
tags:
- name: inventory
  description: Everything about inventory
paths:
  /inventory:
    get:
      tags:
      - inventory
      summary: Get the information of all inventory
      operationId: get_inv
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inventoryInfo'
                x-content-type: application/json
        "404":
          description: Item not found
      x-openapi-router-controller: server.controllers.inventory_controller
    put:
      tags:
      - inventory
      summary: Update a part number
      operationId: update_pn
      requestBody:
        $ref: '#/components/requestBodies/inventoryInfo'
      responses:
        "200":
          description: Ok
        "405":
          description: Invalid input
      x-openapi-router-controller: server.controllers.inventory_controller
    post:
      tags:
      - inventory
      summary: Add a new work order to the server
      operationId: add_pn
      requestBody:
        $ref: '#/components/requestBodies/inventoryInfo'
      responses:
        "200":
          description: Ok
        "405":
          description: Invalid input
      x-openapi-router-controller: server.controllers.inventory_controller
  /inventory/part-number:
    get:
      tags:
      - inventory
      summary: Get the information of a part number
      operationId: get_pn
      parameters:
      - name: part_number
        in: query
        description: This is the input
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inventoryInfo'
                x-content-type: application/json
        "404":
          description: Item not found
      x-openapi-router-controller: server.controllers.inventory_controller
  /inventory/lot-number:
    get:
      tags:
      - inventory
      summary: Get the information of a lot number
      operationId: get_ln
      parameters:
      - name: lot_number
        in: query
        description: This is the input for getting lot number
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryInfo'
        "404":
          description: Item not found
      x-openapi-router-controller: server.controllers.inventory_controller
components:
  schemas:
    inventoryInfo:
      required:
      - part_number
      type: object
      properties:
        part_number:
          type: string
          example: "18300"
        lot_number:
          type: string
          example: R1000
        quantity:
          type: integer
          example: 2000
        last_updated:
          type: string
          example: 7/16/2020 16:38
        location:
          type: string
          example: 4A
        description:
          type: string
          example: Screws
        status:
          type: string
          example: Arrived here
        lead_time:
          type: string
          example: 12 weeks
        outside_process:
          type: string
          example: None
        remarks:
          type: string
          example: Missing
      example:
        last_updated: 7/16/2020 16:38
        quantity: 2000
        outside_process: None
        lead_time: 12 weeks
        part_number: "18300"
        description: Screws
        location: 4A
        lot_number: R1000
        remarks: Missing
        status: Arrived here
  requestBodies:
    inventoryInfo:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inventoryInfo'
      required: true

