openapi: 3.0.0
info:
  description: |
    This is the API for the template microservice.
  version: "1.0.0"
  title: Template Microservice
  contact:
    email: terry.chan@hohokusinc.com
    
tags:
  - name: template
    description: Everything in template

paths:
  /information:
    get:
      tags:
        - template
      summary: Get the information
      operationId: getInfo
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/templateInfo'
        '404':
          description: Item not found
          
    post:
      tags:
        - template
      summary: Add a new info to the server
      operationId: addInfo
      responses:
        '200':
          description: Ok
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/templateInfo'
    put:
      tags:
        - template
      summary: Update info
      operationId: updateInfo
      responses:
        '200':
          description: Ok
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/templateInfo'      

  /information/number:
    get:
      tags:
        - template
      summary: Get the information of a number
      operationId: getNum
      parameters:
        - name: number
          in: query
          required: true
          description: This is the input
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/templateInfo'
        '404':
          description: Item not found

components:
  schemas:
    templateInfo:
      type: object
      required:
        - number
      properties:
        number:
          type: string
          example: 1
        date:
          type: string
          example: 7/16/2020 16:38
        message:
          type: string
          example: Hi there

  requestBodies:
    templateInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/templateInfo'
      required: true