openapi: 3.0.0
info:
  description: |
    This is the inventory microservice.
  version: "1.0.0"
  title: Inventory Microservice
  contact:
    email: terry.chan@hohokusinc.com
    
tags:
  - name: inventory
    description: Everything about inventory

paths:
  /inventory:
    get:
      tags:
        - inventory
      summary: Get the information of all inventory
      operationId: getINV
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inventoryInfo'
        '404':
          description: Item not found
    post:
      tags:
        - inventory
      summary: Add a new work order to the server
      operationId: addPN
      responses:
        '200':
          description: Ok
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/inventoryInfo'
    put:
      tags:
        - inventory
      summary: Update a part number
      operationId: updatePN
      responses:
        '200':
          description: Ok
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/inventoryInfo'      

  /inventory/part-number:
    get:
      tags:
        - inventory
      summary: Get the information of a part number
      operationId: getPN
      parameters:
        - name: part_number
          in: query
          required: true
          description: This is the input
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inventoryInfo'
        '404':
          description: Item not found
        
  /inventory/lot-number:
    get:
      tags:
        - inventory
      summary: Get the information of a lot number
      operationId: getLN
      parameters:
        - name: lot_number
          in: query
          required: true
          description: This is the input for getting lot number
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryInfo'
        '404':
          description: Item not found

components:
  schemas:
    inventoryInfo:
      type: object
      required:
        - part_number
      properties:
        part_number:
          type: string
          example: 18300
        lot_number:
          type: string
          example: R1000
        quantity:
          type: integer
          example: 2000
        last_updated:
          type: string
          example: 7/16/2020 16:38
        location:
          type: string
          example: 4A
        description:
          type: string
          example: Screws
        status:
          type: string
          example: Arrived here
        lead_time:
          type: string
          example: 12 weeks
        outside_process:
          type: string
          example: None
        remarks:
          type: string
          example: Missing

  requestBodies:
    inventoryInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inventoryInfo'
      description: Pet object that needs to be added to the store
      required: true
